@tool
## Compiles a VisualScriptData graph into a GDScript source string.
##
## Usage (from graph_editor.gd):
##   var result := VSGraphCompiler.new().compile(resource)
##   if result["ok"]:
##       var code: String = result["code"]
##
## Design notes:
##   • Execution flow is traced from every "event_*" node following exec-type
##     (PORT_EXEC = 0) right-to-left connections.
##   • Data values are resolved lazily when a node's action expression needs
##     them, recursively following data-type connections backwards.
##   • The Branch node produces an if/else block; all other action nodes
##     produce a single statement then continue the exec chain.
##   • Export-variable nodes are gathered once and emitted at script top-level.
class_name VSGraphCompiler

const NodeDefs := preload("res://addons/visual_scripter/node_definitions.gd")

# ── Public API ────────────────────────────────────────────────────────────────

## Compile *resource* and return a result Dictionary:
##   { "ok": bool, "code": String, "error": String }
func compile(resource: VisualScriptData) -> Dictionary:
	if resource == null:
		return _err("No VisualScriptData resource provided.")

	# Build fast-lookup structures.
	var nodes_by_id:  Dictionary = {}   # id (String) -> node_dict
	var exec_next:    Dictionary = {}   # (from_id, from_port) -> to_id
	var data_source:  Dictionary = {}   # (to_id, to_port) -> {from_id, from_port}

	for node_dict in resource.nodes:
		var nd := node_dict as Dictionary
		nodes_by_id[nd["id"]] = nd

	for conn in resource.connections:
		var cd := conn as Dictionary
		var fid: String = cd["from_node"]
		var fp: int     = cd["from_port"]
		var tid: String = cd["to_node"]
		var tp: int     = cd["to_port"]

		# Categorise by the OUTPUT (right-side) port type of the source node.
		var out_type: int = _right_port_type(fid, fp, nodes_by_id)
		if out_type == NodeDefs.PORT_EXEC:
			exec_next[_key(fid, fp)] = tid
		else:
			data_source[_key(tid, tp)] = {"from_id": fid, "from_port": fp}

	# --- Top-level output ----------------------------------------------------
	var lines: PackedStringArray = PackedStringArray()
	lines.append("# Generated by Visual Scripter – do not edit manually.")
	lines.append("extends " + resource.extends_class)
	lines.append("")

	# @export variable declarations.
	var export_lines := _collect_exports(nodes_by_id)
	for ln: String in export_lines:
		lines.append(ln)
	if not export_lines.is_empty():
		lines.append("")

	# One function per event node.
	var event_types: Array[String] = ["event_physics_process", "event_signal_receiver"]
	var found_event: bool = false
	for raw in resource.nodes:
		var nd := raw as Dictionary
		if (nd["type"] as String) in event_types:
			found_event = true
			var fn_lines := _compile_event(nd["id"], nodes_by_id, exec_next, data_source)
			for ln: String in fn_lines:
				lines.append(ln)
			lines.append("")

	if not found_event:
		return _err("Graph contains no event nodes (_physics_process / Signal Receiver). Nothing to compile.")

	return {"ok": true, "code": "\n".join(lines), "error": ""}


# ── Event compilation ─────────────────────────────────────────────────────────

func _compile_event(
		event_id: String,
		nodes_by_id: Dictionary,
		exec_next: Dictionary,
		data_source: Dictionary) -> PackedStringArray:

	var node_dict: Dictionary = nodes_by_id[event_id]
	var type: String          = node_dict["type"]
	var data: Dictionary      = node_dict.get("data", {})

	var sig_line: String
	match type:
		"event_physics_process":
			sig_line = "func _physics_process(delta: float) -> void:"
		"event_signal_receiver":
			var fname: String = data.get("signal_func", "_on_signal")
			var pname: String = data.get("param_name",  "body")
			sig_line = "func %s(%s: Node) -> void:" % [fname, pname]
		_:
			sig_line = "func _unknown_event() -> void:"

	var lines := PackedStringArray()
	lines.append(sig_line)

	# First exec-out of every event node is always slot-0 right.
	var first_next: String = exec_next.get(_key(event_id, 0), "")
	var body := _compile_chain(first_next, nodes_by_id, exec_next, data_source, "\t")

	if body.is_empty():
		lines.append("\tpass")
	else:
		for ln: String in body:
			lines.append(ln)

	return lines


# ── Execution-chain compilation ───────────────────────────────────────────────

## Recursively compile the execution chain starting at *node_id*.
## Returns an Array of indented GDScript lines (Strings).
func _compile_chain(
		node_id: String,
		nodes_by_id: Dictionary,
		exec_next: Dictionary,
		data_source: Dictionary,
		indent: String) -> PackedStringArray:

	if node_id.is_empty() or not nodes_by_id.has(node_id):
		return PackedStringArray()

	var node_dict: Dictionary = nodes_by_id[node_id]
	var type: String          = node_dict["type"]

	var lines := PackedStringArray()

	# ── Branch node: produces if/else, two sub-chains ─────────────────────────
	if type == "logic_branch":
		var cond: String  = _resolve_data(node_id, 1, nodes_by_id, data_source)
		var true_next: String  = exec_next.get(_key(node_id, 0), "")
		var false_next: String = exec_next.get(_key(node_id, 1), "")

		lines.append(indent + "if " + cond + ":")
		var true_body  := _compile_chain(true_next,  nodes_by_id, exec_next, data_source, indent + "\t")
		if true_body.is_empty():
			lines.append(indent + "\tpass")
		else:
			for ln: String in true_body:
				lines.append(ln)

		lines.append(indent + "else:")
		var false_body := _compile_chain(false_next, nodes_by_id, exec_next, data_source, indent + "\t")
		if false_body.is_empty():
			lines.append(indent + "\tpass")
		else:
			for ln: String in false_body:
				lines.append(ln)

		# Branch itself has no "continue after else" – each arm carries its own chain.
		return lines

	# ── Regular action node ───────────────────────────────────────────────────
	var action_lines := _compile_action(node_id, nodes_by_id, data_source, indent)
	for ln: String in action_lines:
		lines.append(ln)

	# Follow the single exec-out (slot 0 right for all non-branch action nodes).
	var next_id: String = exec_next.get(_key(node_id, 0), "")
	var rest := _compile_chain(next_id, nodes_by_id, exec_next, data_source, indent)
	for ln: String in rest:
		lines.append(ln)

	return lines


# ── Action statement compilation ──────────────────────────────────────────────

func _compile_action(
		node_id: String,
		nodes_by_id: Dictionary,
		data_source: Dictionary,
		indent: String) -> PackedStringArray:

	var node_dict: Dictionary = nodes_by_id[node_id]
	var type: String          = node_dict["type"]
	var data: Dictionary      = node_dict.get("data", {})
	var lines := PackedStringArray()

	match type:

		"action_move_and_slide":
			# Slot 1 = velocity.x input (optional), slot 2 = velocity.y input (optional).
			var vx_key: String = _key(node_id, 1)
			var vy_key: String = _key(node_id, 2)
			if data_source.has(vx_key):
				var vx_expr: String = _resolve_data(node_id, 1, nodes_by_id, data_source)
				lines.append(indent + "velocity.x = " + vx_expr)
			if data_source.has(vy_key):
				var vy_expr: String = _resolve_data(node_id, 2, nodes_by_id, data_source)
				lines.append(indent + "velocity.y = " + vy_expr)
			lines.append(indent + "move_and_slide()")

		"action_animated_sprite_play":
			var node_path: String = data.get("node_path", "AnimatedSprite2D")
			var animation: String = data.get("animation", "idle")
			lines.append(indent + "$%s.play(\"%s\")" % [node_path, animation])

		"action_set_property":
			var node_path: String = data.get("node_path", "").strip_edges()
			var prop: String      = data.get("property", "flip_h")
			var val_expr: String  = _resolve_data(node_id, 1, nodes_by_id, data_source)
			if node_path.is_empty():
				lines.append(indent + "%s = %s" % [prop, val_expr])
			else:
				lines.append(indent + "$%s.%s = %s" % [node_path, prop, val_expr])

		_:
			# Unknown action – emit a comment so the file still parses.
			lines.append(indent + "# TODO: unhandled node type '%s'" % type)

	return lines


# ── Data-value resolution ─────────────────────────────────────────────────────

## Return the GDScript expression that feeds port *port_idx* (left-side) of
## *node_id*, tracing back through data connections recursively.
func _resolve_data(
		node_id: String,
		port_idx: int,
		nodes_by_id: Dictionary,
		data_source: Dictionary) -> String:

	var src = data_source.get(_key(node_id, port_idx), null)
	if src == null:
		# No connection – use a sensible default for the expected port type.
		return _default_for_input(node_id, port_idx, nodes_by_id)

	return _output_expr(src["from_id"], src["from_port"], nodes_by_id, data_source)


## Return the GDScript expression produced by output port *out_port* (right-side)
## of *src_id*, recursively resolving that node's own data inputs if needed.
func _output_expr(
		src_id: String,
		out_port: int,
		nodes_by_id: Dictionary,
		data_source: Dictionary) -> String:

	if not nodes_by_id.has(src_id):
		return "null"

	var node_dict: Dictionary = nodes_by_id[src_id]
	var type: String          = node_dict["type"]
	var data: Dictionary      = node_dict.get("data", {})

	match type:

		"event_physics_process":
			# Slot 1 right = delta float
			if out_port == 1:
				return "delta"

		"event_signal_receiver":
			# Slot 1 right = body (parameter name)
			if out_port == 1:
				return data.get("param_name", "body")

		"input_get_axis":
			var neg: String = data.get("negative_action", "ui_left")
			var pos: String = data.get("positive_action", "ui_right")
			return "Input.get_axis(\"%s\", \"%s\")" % [neg, pos]

		"input_is_action_just_pressed":
			var action: String = data.get("action", "ui_accept")
			return "Input.is_action_just_pressed(\"%s\")" % action

		"math_multiply":
			var a: String = _resolve_data(src_id, 0, nodes_by_id, data_source)
			var b: String = _resolve_data(src_id, 1, nodes_by_id, data_source)
			return "(%s * %s)" % [a, b]

		"variable_export":
			return data.get("var_name", "variable")

	return "null"


# ── Export-variable gathering ─────────────────────────────────────────────────

func _collect_exports(nodes_by_id: Dictionary) -> PackedStringArray:
	var lines := PackedStringArray()
	for raw in nodes_by_id.values():
		var node_dict := raw as Dictionary
		if node_dict["type"] != "variable_export":
			continue
		var data: Dictionary = node_dict.get("data", {})
		var vname: String    = data.get("var_name",      "my_var")
		var vtype: String    = data.get("var_type",      "float")
		var vdefault: String = data.get("default_value", "0.0")
		lines.append("@export var %s: %s = %s" % [vname, vtype, vdefault])
	return lines


# ── Utility ───────────────────────────────────────────────────────────────────

## Compound key for (node_id, port_index) lookup dictionaries.
func _key(node_id: String, port: int) -> String:
	return node_id + ":" + str(port)


## Port type of the right (output) side of *port_idx* on *node_id*.
func _right_port_type(node_id: String, port_idx: int, nodes_by_id: Dictionary) -> int:
	var node_dict = nodes_by_id.get(node_id, null)
	if node_dict == null:
		return -1
	var def = NodeDefs.DEFINITIONS.get(node_dict["type"], null)
	if def == null:
		return -1
	var slots: Array = def.get("slots", [])
	if port_idx >= slots.size():
		return -1
	return slots[port_idx].get("right_type", -1)


## Return a hard-coded default expression when no data connection is present.
func _default_for_input(node_id: String, port_idx: int, nodes_by_id: Dictionary) -> String:
	var node_dict = nodes_by_id.get(node_id, null)
	if node_dict == null:
		return "null"
	var def = NodeDefs.DEFINITIONS.get(node_dict["type"], null)
	if def == null:
		return "null"
	var slots: Array = def.get("slots", [])
	if port_idx >= slots.size():
		return "null"
	var port_type: int = slots[port_idx].get("left_type", -1)
	match port_type:
		NodeDefs.PORT_BOOL:   return "false"
		NodeDefs.PORT_INT:    return "0"
		NodeDefs.PORT_FLOAT:  return "0.0"
		NodeDefs.PORT_STRING: return '""'
		_:                    return "null"


func _err(msg: String) -> Dictionary:
	return {"ok": false, "code": "", "error": msg}
